In [1]:
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
import os
import time
import pandas as pd
from scipy.spatial.distance import cosine
import pickle
from tqdm import tqdm

/Users/jayantadey/miniconda3/envs/efri/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [31]:
dataset = pd.read_excel('./trauma_data/embedding_responses_jan28.xlsx', sheet_name="EXPERT")

total_response = 4

res = dataset['Value 1']
for ii in range(total_response-1):
    res += dataset['Value '+str(ii+2)]
res /= total_response

dataset['score'] = res

In [32]:
dataset.head()

,Response 1,Response 2,Value 1,Value 2,Value 3,Value 4,score
0,Obtain a trauma series of xrays followed by a ...,Perform primary trauma survey with attention t...,2,2,3.0,4.0,2.75
1,"Primary, secondary survey, X-ray of RLE to eva...",splint the leg and transfer them to a level 1 ...,3,4,4.0,1.0,3.00
2,Immediate transfer to trauma center. Consider ...,Stabilize and transfer,2,5,4.0,3.0,3.50
3,"1. Check VS and perform a primary survey, obta...","Primary Survey, follow ATLS, CXR/PXR w/ RLE im...",2,2,4.0,5.0,3.25
4,Transfer emergently to a Level 1 or 2 trauma c...,"I would obtain an anticoagulation history, ass...",3,5,4.0,5.0,4.25

In [10]:
# Load dataset
#dataset = load_dataset("sentence-transformers/stsb", split="train")
dataset = load_dataset("tabilab/biosses", split="train")
print(f"Loaded {len(dataset)} examples. Sample:")
print(dataset[0], "\n")

Generating train split: 100%|██████████| 100/100 [00:00<00:00, 1784.57 examples/s]

Loaded 100 examples. Sample:
{'sentence1': 'Here, looking for agents that could specifically kill KRAS mutant cells, they found that knockdown of GATA2 was synthetically lethal with KRAS mutation', 'sentence2': 'Not surprisingly, GATA2 knockdown in KRAS mutant cells resulted in a striking reduction of active GTP-bound RHO proteins, including the downstream ROCK kinase', 'score': 2.200000047683716}

In [21]:
# Generate embeddings for the first few sentence pairs (do not run without need, save results, costs money)
#model_name = 'nomic-ai/nomic-embed-text-v2-moe'#'nomic-embed-text-v1.5'
folder_name = "Snowflake/"
model_name = "snowflake-arctic-embed-l-v2.0"
dims = [768]#[64, 256, 512, 768]

for dim in dims:
    print('Doing dimension ', dim)
    file_to_save = './biosses/snowflake_text-'+model_name+'_'+str(dim)+'.pickle'#+'_non_expert.pickle'
    embeddings = pd.DataFrame()
    sentence1 = []
    sentence2 = []
    embedding1 = []
    embedding2 = []
    cosine_similarity = []
    human_score = []

    model = SentenceTransformer(folder_name+model_name, trust_remote_code=True, truncate_dim=64)

    print('Extracting embedding and measuring similarity ...')
    time.sleep(1)
    for idx in tqdm(range(len(dataset))):
        #first_sentence = dataset["Response 1"][idx]
        first_sentence = dataset["sentence1"][idx]
        emb1 = response = list(model.encode(first_sentence))
        sentence1.append(
            first_sentence
        )
        embedding1.append(
            emb1
        )
        #############################
        #second_sentence = dataset["Response 2"][idx]
        second_sentence = dataset["sentence2"][idx]
        emb2 = list(model.encode(second_sentence))
        sentence2.append(
            second_sentence
        )
        embedding2.append(
            emb2
        )
        
        ############################
        cosine_similarity.append(
            1 - cosine(emb1, emb2)
        )
        human_score.append(
            dataset["score"][idx]/4.0#/4.0 #comment out this depending on the data
        )
        
        time.sleep(1)  # respect rate limits!

    embeddings['Sentence 1'] = sentence1
    embeddings['Sentence 2'] = sentence2
    embeddings['Embedding of Sentence 1'] = embedding1
    embeddings['Embedding of Sentence 2'] = embedding2
    embeddings['Cosine similarity'] = cosine_similarity
    embeddings['Human score'] = human_score

    with open(file_to_save, 'wb') as f:
        pickle.dump(embeddings, f)

Doing dimension  768

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 19435.33it/s]

Extracting embedding and measuring similarity ...

100%|██████████| 100/100 [01:52<00:00,  1.13s/it]

In [22]:
embeddings.head()

,Sentence 1,Sentence 2,Embedding of Sentence 1,Embedding of Sentence 2,Cosine similarity,Human score
0,"Here, looking for agents that could specifical...","Not surprisingly, GATA2 knockdown in KRAS muta...","[0.044200413, 0.09844565, 0.024286913, -0.0457...","[0.09266666, 0.043897014, -0.03221333, -0.0018...",0.715659,0.55
1,MLL-FKBP and MLL-AF9 transformed cells showed ...,Regardless of the mechanism for transcriptiona...,"[0.029856253, -0.03897464, -0.02909082, 0.0338...","[0.021858666, -0.0026523846, -0.013961511, 0.0...",0.648718,0.80
2,The oncogenic activity of mutant Kras appears ...,Oncogenic KRAS mutations are common in cancer.,"[0.082608856, 0.08117444, -0.003984815, -0.004...","[0.033162355, 0.059290092, -0.05656486, -0.025...",0.747905,0.50
3,Consequently miRNAs have been demonstrated to ...,Given the extensive involvement of miRNA in ph...,"[0.018506765, 0.042937428, 0.023957042, 0.0004...","[0.035150398, -0.0020378034, 0.03515339, 0.018...",0.626309,0.70
4,We then sought to reassess the regulation of m...,"Importantly, our reassessment revealed that th...","[-0.021350216, -0.006749561, 0.06495994, -0.00...","[0.035011746, -0.011642246, 0.02338437, 0.0617...",0.488291,0.60